version: '2'
services:
    web:
        build: .
        ports:
            - "5123:5123"
        networks:
          - web
        volumes:
            - ./www:/myapp
        restart: always
        labels:
          traefik.enable: true
          traefik.port: 5123
          traefik.frontend.rule: "Host:mlcc.janamarie.dev"
          traefik.frontend.redirect.entryPoint: "https"
          traefik.docker.network: web

networks:
  web:
    external: true


